# Energy data for Dallas

### Energy Prices Dallas

In [9]:
import pandas as pd
from gridstatus.ercot import Ercot

iso = Ercot()

prices = iso.get_rtm_spp(2025)

print(prices.head())
print(prices.columns)
print(prices.shape)

2026-05-17 16:07:11 - INFO - Fetching document https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=13061&_1779052031
2026-05-17 16:07:11 - INFO - Requesting https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=13061&_1779052031 with {}
2026-05-17 16:09:03 - INFO - Fetching document https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=10008&_1779052143
2026-05-17 16:09:03 - INFO - Requesting https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=10008&_1779052143 with {}
2026-05-17 16:09:04 - INFO - Fetching https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1226159167

                       Time            Interval Start  \
0 2025-01-01 00:00:00-06:00 2025-01-01 00:00:00-06:00
1 2025-01-01 00:00:00-06:00 2025-01-01 00:00:00-06:00
2 2025-01-01 00:00:00-06:00 2025-01-01 00:00:00-06:00
3 2025-01-01 00:00:00-06:00 2025-01-01 00:00:00-06:00
4 2025-01-01 00:00:00-06:00 2025-01-01 00:00:00-06:00

               Interval End    Location Location Type            Market   SPP
0 2025-01-01 00:15:00-06:00   HB_BUSAVG   Trading Hub  REAL_TIME_15_MIN  17.9
1 2025-01-01 00:15:00-06:00  HB_HOUSTON   Trading Hub  REAL_TIME_15_MIN  17.9
2 2025-01-01 00:15:00-06:00    LZ_RAYBN     Load Zone  REAL_TIME_15_MIN  17.9
3 2025-01-01 00:15:00-06:00     LZ_WEST     Load Zone  REAL_TIME_15_MIN  17.9
4 2025-01-01 00:15:00-06:00   HB_HUBAVG   Trading Hub  REAL_TIME_15_MIN  17.9
Index(['Time', 'Interval Start', 'Interval End', 'Location', 'Location Type',
       'Market', 'SPP'],
      dtype='object')
(805920, 7)

In [10]:
prices.columns.tolist()

['Time',
 'Interval Start',
 'Interval End',
 'Location',
 'Location Type',
 'Market',
 'SPP']

In [11]:
prices["Location"].unique()[:20]

<StringArray>
[ 'HB_BUSAVG', 'HB_HOUSTON',   'LZ_RAYBN',    'LZ_WEST',  'HB_HUBAVG',
   'LZ_SOUTH',     'LZ_CPS',     'HB_PAN',   'HB_NORTH',   'LZ_NORTH',
 'LZ_HOUSTON',     'LZ_AEN',    'LZ_LCRA',   'HB_SOUTH',    'HB_WEST']
Length: 15, dtype: string

In [12]:
north_prices = prices[
    prices["Location"].isin([
        "HB_NORTH",
        "LZ_NORTH"
    ])
]

north_prices.head()

,Time,Interval Start,Interval End,Location,Location Type,Market,SPP
11,2025-01-01 00:00:00-06:00,2025-01-01 00:00:00-06:00,2025-01-01 00:15:00-06:00,HB_NORTH,Trading Hub,REAL_TIME_15_MIN,17.90
12,2025-01-01 00:00:00-06:00,2025-01-01 00:00:00-06:00,2025-01-01 00:15:00-06:00,LZ_NORTH,Load Zone,REAL_TIME_15_MIN,17.90
20,2025-01-01 00:00:00-06:00,2025-01-01 00:00:00-06:00,2025-01-01 00:15:00-06:00,LZ_NORTH,Load Zone,REAL_TIME_15_MIN,17.90
30,2025-01-01 00:15:00-06:00,2025-01-01 00:15:00-06:00,2025-01-01 00:30:00-06:00,HB_NORTH,Trading Hub,REAL_TIME_15_MIN,17.98
33,2025-01-01 00:15:00-06:00,2025-01-01 00:15:00-06:00,2025-01-01 00:30:00-06:00,LZ_NORTH,Load Zone,REAL_TIME_15_MIN,17.98

In [14]:
north_prices.to_csv(
    "data/raw/ercot_prices/north_texas_prices_2025.csv",
    index=False
)

### Energy Demand Location Dallas

In [17]:
import pandas as pd
from gridstatus.ercot import Ercot

iso = Ercot()

load = iso.get_load_by_weather_zone(
    date=pd.Timestamp("2025-01-01")
)

print(load.head())
print(load.columns)
print(load.shape)

2026-05-17 16:17:44 - INFO - Fetching document https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=13101&_1779052664
2026-05-17 16:17:44 - INFO - Requesting https://www.ercot.com/misapp/servlets/IceDocListJsonWS?reportTypeId=13101&_1779052664 with {}

NoDataFoundException: No documents found with the given parameters: {'report_type_id': 13101, 'date': Timestamp('2025-01-02 00:00:00-0600', tz='US/Central'), 'published_after': None, 'published_before': None, 'friendly_name_timestamp_after': None, 'friendly_name_timestamp_before': None, 'constructed_name_contains': 'csv.zip', 'extension': None, 'verbose': False, 'base_url': 'www.ercot.com', 'request_kwargs': None, 'matches': [], 'doc': {'Document': {'ExpiredDate': '2026-05-17T23:59:59-05:00', 'ILMStatus': 'EXT', 'SecurityStatus': 'P', 'ContentSize': '1864', 'Extension': 'zip', 'ReportTypeID': '13101', 'Prefix': 'cdr', 'FriendlyName': 'ACTUALSYSLOADWZNP6345_xml', 'ConstructedName': 'cdr.00013101.0000000000000000.20260416.055000373.ACTUALSYSLOADWZNP6345_xml.zip', 'DocID': '1216006930', 'PublishDate': '2026-04-16T05:50:00-05:00', 'ReportName': 'Actual System Load by Weather Zone', 'DUNS': '0000000000000000', 'DocCount': '0'}}, 'match': False, 'doc_url': 'https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1216006930', 'friendly_name_timestamp': None, 'friendly_name': 'ACTUALSYSLOADWZNP6345_xml', 'publish_date': Timestamp('2026-04-16 05:50:00-0500', tz='US/Central'), 'doc_obj': Document(url='https://www.ercot.com/misdownload/servlets/mirDownload?doclookupId=1216006930', publish_date=Timestamp('2026-04-16 05:50:00-0500', tz='US/Central'), constructed_name='cdr.00013101.0000000000000000.20260416.055000373.ACTUALSYSLOADWZNP6345_xml.zip', friendly_name='ACTUALSYSLOADWZNP6345_xml', friendly_name_timestamp=None)}

In [ ]:
load.to_csv(
    "data/raw/ercot_load/weather_zone_load_2025.csv",
    index=False
)

### Energy Generation Mix Dallas

# Weather data Dallas

In [ ]:
# pull Dallas weather data
import pandas as pd
from datetime import date, timedelta

station = "USW00003927"  # Dallas Love Field
end_date = date.today()
start_date = end_date - timedelta(days=365)

url = (
    "https://www.ncei.noaa.gov/access/services/data/v1"
    "?dataset=daily-summaries"
    f"&stations={station}"
    f"&startDate={start_date}"
    f"&endDate={end_date}"
    "&dataTypes=TAVG,TMAX,TMIN,PRCP,SNOW,SNWD"
    "&units=standard"
    "&format=json"
)

raw = pd.read_json(url)

print(raw.columns)  # inspect what NOAA actually returned

weather = raw.rename(columns={
    "DATE": "weather_date",
    "TAVG": "temp_avg",
    "TMAX": "temp_max",
    "TMIN": "temp_min",
    "PRCP": "precipitation",
    "SNOW": "snowfall",
    "SNWD": "snow_depth"
})

# Create missing columns if NOAA did not return them
for col in ["temp_avg", "temp_max", "temp_min", "precipitation", "snowfall", "snow_depth"]:
    if col not in weather.columns:
        weather[col] = pd.NA

# Convert numeric columns first
numeric_cols = ["temp_avg", "temp_max", "temp_min", "precipitation", "snowfall", "snow_depth"]

for col in numeric_cols:
    weather[col] = pd.to_numeric(weather[col], errors="coerce")

# If TAVG is missing, approximate average temperature from max/min
weather["temp_avg"] = weather["temp_avg"].fillna(
    (weather["temp_max"] + weather["temp_min"]) / 2
)

weather["weather_date"] = pd.to_datetime(weather["weather_date"]).dt.strftime("%-m/%-d/%y")

weather[["precipitation", "snowfall", "snow_depth"]] = weather[
    ["precipitation", "snowfall", "snow_depth"]
].fillna(0)

cols = [
    "weather_date",
    "temp_avg",
    "temp_max",
    "temp_min",
    "precipitation",
    "snowfall",
    "snow_depth"
]

weather = weather[cols]

weather.to_csv("data/raw/weather/dallas_weather_past_year.csv", index=False)

weather.head()

Index(['DATE', 'STATION', 'SNOW', 'TMAX', 'TMIN', 'PRCP', 'SNWD'], dtype='object')

,weather_date,temp_avg,temp_max,temp_min,precipitation,snowfall,snow_depth
0,5/17/25,81.5,91,72,0.07,0.0,0.0
1,5/18/25,79.5,85,74,0.10,0.0,0.0
2,5/19/25,76.5,85,68,0.22,0.0,0.0
3,5/20/25,75.0,84,66,0.00,0.0,0.0
4,5/21/25,74.5,88,61,0.00,0.0,0.0